# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multiplyXtXBySparse_c <- function(n, ind, val, phi, w) {
    .Call('_cnvJoint_multiplyXtXBySparse_c', PACKAGE = 'cnvJoint', n, ind, val, phi, w)
}

leftMultiplyByXt_c <- function(Y, phi, w) {
    .Call('_cnvJoint_leftMultiplyByXt_c', PACKAGE = 'cnvJoint', Y, phi, w)
}

leftMultiplyByInvXAtXA_c <- function(n, ind, val, phi, w) {
    .Call('_cnvJoint_leftMultiplyByInvXAtXA_c', PACKAGE = 'cnvJoint', n, ind, val, phi, w)
}

ic_c <- function(k, Y, phi, theta, p, n) {
    .Call('_cnvJoint_ic_c', PACKAGE = 'cnvJoint', k, Y, phi, theta, p, n)
}

defaultWeights_c <- function(p) {
    .Call('_cnvJoint_defaultWeights_c', PACKAGE = 'cnvJoint', p)
}

doLars_c <- function(Y, K, phi, wts, p, n, epsilon = 1e-09) {
    .Call('_cnvJoint_doLars_c', PACKAGE = 'cnvJoint', Y, K, phi, wts, p, n, epsilon)
}

cnv_c <- function(Y, tau1, wts, steps, maxloop = 10L) {
    .Call('_cnvJoint_cnv_c', PACKAGE = 'cnvJoint', Y, tau1, wts, steps, maxloop)
}

get_f <- function(Y, sigma, delta) {
    .Call('_cnvJoint_get_f', PACKAGE = 'cnvJoint', Y, sigma, delta)
}

get_g <- function(Y, sigma, delta2) {
    .Call('_cnvJoint_get_g', PACKAGE = 'cnvJoint', Y, sigma, delta2)
}

get_f_and_g <- function(sigma, delta, Y) {
    .Call('_cnvJoint_get_f_and_g', PACKAGE = 'cnvJoint', sigma, delta, Y)
}

get_alpha <- function(Y, alpha, rho, c, sigma, delta) {
    .Call('_cnvJoint_get_alpha', PACKAGE = 'cnvJoint', Y, alpha, rho, c, sigma, delta)
}

grdesc <- function(Y, sig, del, maxit) {
    .Call('_cnvJoint_grdesc', PACKAGE = 'cnvJoint', Y, sig, del, maxit)
}

